2013/08/04 21:40:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:41:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/default/login".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/default/log...')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii/default/login
---
2013/08/04 22:28:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:29:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:29:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:29:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:31:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:31:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:31:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:31:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:31:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:31:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:31:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:31:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:31:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:32:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:32:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:32:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:32:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:32:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:32:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:32:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:33:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:33:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:34:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
